// Rune and runeword data for the Rune Tab tool.
//
// RUNES: number, name, character level required.
// RUNE_LAYOUT: rows of rune names as they appear in the stash Runes tab.
//   Edit this to change how the grid is arranged.
// RUNEWORDS: one entry per runeword.
//   slots   – item slots the runeword can be made in: weapon | armor | helm | shield
//   bases   – allowed base item types, as shown in game
//   level   – required character level
//   patch   – game version the runeword was added in
// RUNEWORD_TIERS: maxroll.gg Runeword Tier List (S best … F worst).
// BUILDS: maxroll.gg Late Game Tier List builds and the runewords each build
//   guide uses on the character (`uses`) and on the mercenary (`merc`).
//   Class usefulness is derived from these.

export const RUNES = [
  ["El", 11], ["Eld", 11], ["Tir", 13], ["Nef", 13], ["Eth", 15], ["Ith", 15],
  ["Tal", 17], ["Ral", 19], ["Ort", 21], ["Thul", 23], ["Amn", 25], ["Sol", 27],
  ["Shael", 29], ["Dol", 31], ["Hel", 33], ["Io", 35], ["Lum", 37], ["Ko", 39],
  ["Fal", 41], ["Lem", 43], ["Pul", 45], ["Um", 47], ["Mal", 49], ["Ist", 51],
  ["Gul", 53], ["Vex", 55], ["Ohm", 57], ["Lo", 59], ["Sur", 61], ["Ber", 63],
  ["Jah", 65], ["Cham", 67], ["Zod", 69],
].map(([name, level], i) => ({ name, level, number: i + 1 }));

// Matches the in-game Runes tab: 9 columns, with the last runes wrapping
// around the Horadric Cube in the middle (null = empty space).
export const RUNE_LAYOUT = [
  ["El", "Eld", "Tir", "Nef", "Eth", "Ith", "Tal", "Ral", "Ort"],
  ["Thul", "Amn", "Sol", "Shael", "Dol", "Hel", "Io", "Lum", "Ko"],
  ["Fal", "Lem", "Pul", "Um", "Mal", "Ist", "Gul", "Vex", "Ohm"],
  ["Lo", "Sur", null, null, null, null, null, "Ber", "Jah"],
  ["Cham", null, null, null, null, null, null, null, "Zod"],
];

export const CLASSES = [
  ["ama", "Amazon"], ["asn", "Assassin"], ["bar", "Barbarian"], ["dru", "Druid"],
  ["nec", "Necromancer"], ["pal", "Paladin"], ["sor", "Sorceress"], ["war", "Warlock"],
  ["merc", "Mercenary"],
];

export const SLOTS = [
  ["weapon", "Weapons"], ["armor", "Body Armor"], ["helm", "Helms"], ["shield", "Shields"],
];

export const RUNEWORDS = [
  { name: "Enigma", runes: ["Jah", "Ith", "Ber"], slots: ["armor"], bases: ["Body Armor"], level: 65, patch: "1.10",
    stats: ["+2 to All Skills", "+45% Faster Run/Walk", "+1 to Teleport", "+750-775 Defense", "+0.75 to Strength (per level)", "Increase Maximum Life 5%", "Damage Reduced by 8%", "+14 Life after each Kill", "15% Damage Taken Goes To Mana", "1-99% Better Chance of Getting Magic Items (per level)"] },
  { name: "Call to Arms", runes: ["Amn", "Ral", "Mal", "Ist", "Ohm"], slots: ["weapon"], bases: ["All Weapons"], level: 57, patch: "1.10",
    stats: ["+1 to All Skills", "+40% Increased Attack Speed", "+250-290% Enhanced Damage", "+2-6 to Battle Command", "+1-6 to Battle Orders", "+1-4 to Battle Cry", "Prevent Monster Heal", "30% Better Chance of Getting Magic Items"] },
  { name: "Spirit", runes: ["Tal", "Thul", "Ort", "Amn"], slots: ["weapon", "shield"], bases: ["Swords", "Shields"], level: 25, patch: "1.11",
    stats: ["+2 to All Skills", "+25-35% Faster Cast Rate", "+55% Faster Hit Recovery", "+250 Defense vs. Missile", "+22 to Vitality", "+89-112 to Mana", "Magic Damage Taken Reduced by 3-8"] },
  { name: "Insight", runes: ["Ral", "Tir", "Tal", "Sol"], slots: ["weapon"], bases: ["Polearms", "Staves", "Bows", "Crossbows"], level: 27, patch: "1.10",
    stats: ["Level 12-17 Meditation Aura When Equipped", "+35% Faster Cast Rate", "+200-260% Enhanced Damage", "+1-6 to Critical Strike", "+5 to All Attributes", "+2 to Mana after each Kill", "23% Better Chance of Getting Magic Items"] },
  { name: "Infinity", runes: ["Ber", "Mal", "Ber", "Ist"], slots: ["weapon"], bases: ["Polearms", "Spears"], level: 63, patch: "1.10",
    stats: ["Level 12 Conviction Aura When Equipped", "50% Chance to Cast Level 20 Chain Lightning When You Kill an Enemy", "+35% Faster Run/Walk", "+255-325% Enhanced Damage", "-45-55% to Enemy Lightning Resistance", "40% Chance of Crushing Blow", "Prevent Monster Heal", "30% Better Chance of Getting Magic Items"] },
  { name: "Heart of the Oak", runes: ["Ko", "Vex", "Pul", "Thul"], slots: ["weapon"], bases: ["Staves", "Maces"], level: 55, patch: "1.10",
    stats: ["+3 to All Skills", "+40% Faster Cast Rate", "+75% Damage to Demons", "Adds 3-14 Cold Damage", "3% Mana Stolen per Hit", "+10 to Dexterity", "Replenish Life +20", "Increase Maximum Mana 15%", "All Resistances +30-40", "Level 4 Oak Sage (25 Charges)", "Level 14 Raven (60 Charges)"] },
  { name: "Chains of Honor", runes: ["Dol", "Um", "Ber", "Ist"], slots: ["armor"], bases: ["Body Armor"], level: 63, patch: "1.10",
    stats: ["+2 to All Skills", "+200% Damage to Demons", "+100% Damage to Undead", "8% Life Stolen per Hit", "+70% Enhanced Defense", "+20 to Strength", "Replenish Life +7", "All Resistances +65", "Damage Reduced by 8%", "25% Better Chance of Getting Magic Items"] },
  { name: "Grief", runes: ["Eth", "Tir", "Lo", "Mal", "Ral"], slots: ["weapon"], bases: ["Swords", "Axes"], level: 59, patch: "1.10",
    stats: ["35% Chance to Cast Level 15 Venom on Striking", "+30-40% Increased Attack Speed", "Damage +340-400", "Ignore Target's Defense", "-25% Target Defense", "+(1.875 per level)% Damage to Demons", "Adds 5-30 Fire Damage", "-20-25% to Enemy Poison Resistance", "20% Deadly Strike", "Prevent Monster Heal", "+2 to Mana after each Kill", "+10-15 Life after each Kill"] },
  { name: "Fortitude", runes: ["El", "Sol", "Dol", "Lo"], slots: ["weapon", "armor"], bases: ["Weapons", "Body Armor"], level: 59, patch: "1.10",
    stats: ["20% Chance to Cast Level 15 Chilling Armor when Struck", "+25% Faster Cast Rate", "+300% Enhanced Damage", "+200% Enhanced Defense", "+15 Defense", "+(1-1.5 per level) to Life", "Replenish Life +7", "+5% to Maximum Lightning Resist", "All Resistances +25-30", "Damage Reduced by 7", "12% Damage Taken Goes to Mana", "25% Better Chance of Getting Magic Items"] },
  { name: "Stealth", runes: ["Tal", "Eth"], slots: ["armor"], bases: ["Body Armor"], level: 17, patch: "1.09",
    stats: ["Magic Damage Reduced by 3", "+6 to Dexterity", "+15 to Maximum Stamina", "Poison Resist +30%", "Regenerate Mana 15%", "+25% Faster Run/Walk", "+25% Faster Cast Rate", "+25% Faster Hit Recovery"] },
  { name: "Lore", runes: ["Ort", "Sol"], slots: ["helm"], bases: ["Helms"], level: 27, patch: "1.09",
    stats: ["+1 to All Skills", "+10 to Energy", "Lightning Resist +30%", "Damage Reduced by 7", "+2 to Mana after each Kill", "+2 to Light Radius"] },
  { name: "Mosaic", runes: ["Mal", "Gul", "Amn"], slots: ["weapon"], bases: ["Claws"], level: 53, patch: "2.6",
    stats: ["50% Chance for Finishing Moves to Not Consume Charges", "+2 to Martial Arts (Assassin Only)", "+20% Increased Attack Speed", "+200-250% Enhanced Damage", "+20% Bonus to Attack Rating", "7% Life Stolen per Hit", "+8-15% to Cold Skill Damage", "+8-15% to Lightning Skill Damage", "+8-15% to Fire Skill Damage", "Prevent Monster Heal"] },

  { name: "Beast", runes: ["Ber", "Tir", "Um", "Mal", "Lum"], slots: ["weapon"], bases: ["Axes", "Scepters", "Hammers"], level: 63, patch: "1.10",
    stats: ["Level 9 Fanaticism Aura When Equipped", "+40% Increased Attack Speed", "+240-270% Enhanced Damage", "20% Chance of Crushing Blow", "25% Chance of Open Wounds", "+3 to Werebear", "+3 to Lycanthropy", "Prevent Monster Heal", "+25-40 to Strength", "+10 to Energy", "+2 to Mana after each Kill", "Level 13 Summon Grizzly (5 Charges)"] },
  { name: "Bone", runes: ["Sol", "Um", "Um"], slots: ["armor"], bases: ["Body Armor"], level: 47, patch: "1.11",
    stats: ["15% Chance to Cast Level 10 Bone Armor when Struck", "15% Chance to Cast Level 10 Bone Spear on Striking", "+2 to Necromancer Skill Levels", "+100-150 to Mana", "All Resistances +30", "Damage Reduced by 7"] },
  { name: "Bramble", runes: ["Ral", "Ohm", "Sur", "Eth"], slots: ["armor"], bases: ["Body Armor"], level: 61, patch: "1.10",
    stats: ["Level 15-21 Thorns Aura When Equipped", "+50% Faster Hit Recovery", "+15-21% to Poison Skill Damage", "+300 Defense vs. Missile", "Increase Maximum Mana 5%", "Regenerate Mana 15%", "+5% to Maximum Cold Resist", "Fire Resist +30%", "Poison Resist +100%", "+13 Life after each Kill", "Level 13 Spirit of Barbs (33 Charges)"] },
  { name: "Breath of the Dying", runes: ["Vex", "Hel", "El", "Eld", "Zod", "Eth"], slots: ["weapon"], bases: ["All Weapons"], level: 69, patch: "1.10",
    stats: ["50% Chance to Cast Level 20 Poison Nova When You Kill an Enemy", "Indestructible", "+60% Increased Attack Speed", "+350-400% Enhanced Damage", "+200% Damage to Undead", "-25% Target Defense", "+50 to Attack Rating", "7% Mana Stolen per Hit", "12-15% Life Stolen per Hit", "Prevent Monster Heal", "+30 to All Attributes", "+1 to Light Radius"] },
  { name: "Crescent Moon", runes: ["Shael", "Um", "Tir"], slots: ["weapon"], bases: ["Axes", "Swords", "Polearms"], level: 47, patch: "1.10",
    stats: ["10% Chance to Cast Level 17 Chain Lightning on Striking", "7% Chance to Cast Level 13 Static Field on Striking", "+20% Increased Attack Speed", "+180-220% Enhanced Damage", "Ignore Target's Defense", "-35% to Enemy Lightning Resistance", "25% Chance of Open Wounds", "+9-11 Magic Absorb", "+2 to Mana after each Kill", "Level 18 Summon Spirit Wolf (30 Charges)"] },
  { name: "Death", runes: ["Hel", "El", "Vex", "Ort", "Gul"], slots: ["weapon"], bases: ["Swords", "Axes"], level: 55, patch: "1.10",
    stats: ["Indestructible", "100% Chance to Cast Level 44 Chain Lightning When You Die", "25% Chance to Cast Level 18 Glacial Spike on Attack", "+300-385% Enhanced Damage", "20% Bonus to Attack Rating", "+50 to Attack Rating", "Adds 1-50 Lightning Damage", "7% Mana Stolen per Hit", "50% Chance of Crushing Blow", "(0.5 per level)% Deadly Strike", "+1 to Light Radius", "Level 22 Blood Golem (15 Charges)"] },
  { name: "Doom", runes: ["Hel", "Ohm", "Um", "Lo", "Cham"], slots: ["weapon"], bases: ["Axes", "Polearms", "Hammers"], level: 67, patch: "1.10",
    stats: ["5% Chance to Cast Level 18 Volcano on Striking", "Level 12 Holy Freeze Aura When Equipped", "+2 to All Skills", "+45% Increased Attack Speed", "+330-370% Enhanced Damage", "-40-60% to Enemy Cold Resistance", "20% Deadly Strike", "25% Chance of Open Wounds", "Prevent Monster Heal", "Freezes Target +3"] },
  { name: "Dream", runes: ["Io", "Jah", "Pul"], slots: ["helm", "shield"], bases: ["Helms", "Shields"], level: 65, patch: "1.10",
    stats: ["10% Chance to Cast Level 15 Confuse When Struck", "Level 15 Holy Shock Aura When Equipped", "+20-30% Faster Hit Recovery", "+30% Enhanced Defense", "+150-220 Defense", "+10 to Vitality", "Increase Maximum Life 5%", "+(0.625 per level) to Mana", "All Resistances +5-20", "12-25% Better Chance of Getting Magic Items"] },
  { name: "Exile", runes: ["Vex", "Ohm", "Ist", "Dol"], slots: ["shield"], bases: ["Paladin Shields"], level: 57, patch: "1.10",
    stats: ["15% Chance to Cast Level 5 Life Tap on Striking", "Level 13-16 Defiance Aura When Equipped", "+2 to Offensive Auras (Paladin Only)", "+30% Faster Block Rate", "Freezes Target", "+220-260% Enhanced Defense", "Replenish Life +7", "+5% to Maximum Cold Resist", "+5% to Maximum Fire Resist", "25% Better Chance of Getting Magic Items", "Repairs 1 Durability in 4 Seconds"] },
  { name: "Faith", runes: ["Ohm", "Jah", "Lem", "Eld"], slots: ["weapon"], bases: ["Bows", "Crossbows"], level: 65, patch: "1.10",
    stats: ["Level 12-15 Fanaticism Aura When Equipped", "+1-2 to All Skills", "+330% Enhanced Damage", "Ignore Target's Defense", "300% Bonus to Attack Rating", "+75% Damage to Undead", "+50 to Attack Rating Against Undead", "+120 Fire Damage", "All Resistances +15", "10% Reanimate As: Returned", "75% Extra Gold from Monsters"] },
  { name: "Fury", runes: ["Jah", "Gul", "Eth"], slots: ["weapon"], bases: ["Melee Weapons"], level: 65, patch: "1.09",
    stats: ["+40% Increased Attack Speed", "+209% Enhanced Damage", "Ignore Target's Defense", "-25% Target Defense", "20% Bonus to Attack Rating", "6% Life Stolen per Hit", "33% Deadly Strike", "66% Chance of Open Wounds", "+5 to Frenzy (Barbarian Only)", "Prevent Monster Heal"] },
  { name: "Honor", runes: ["Amn", "El", "Ith", "Tir", "Sol"], slots: ["weapon"], bases: ["Melee Weapons"], level: 27, patch: "1.09",
    stats: ["+1 to All Skills", "+160% Enhanced Damage", "+9 to Minimum Damage", "+9 to Maximum Damage", "25% Deadly Strike", "+250 to Attack Rating", "7% Life Stolen per Hit", "+10 to Strength", "Replenish Life +10", "+2 to Mana after each Kill", "+1 to Light Radius"] },
  { name: "Mania", runes: ["Shael", "Ko", "Eld"], slots: ["weapon"], bases: ["All Weapons"], level: 39, patch: "3.0",
    note: "Weapon half of the former Hustle",
    stats: ["5% Chance to Cast Level 1 Burst of Speed on Striking", "Level 1 Fanaticism Aura When Equipped", "+30% Increased Attack Speed", "+180-200% Enhanced Damage", "+75% Damage to Undead", "+50 to Attack Rating against Undead", "+10 to Dexterity"] },
  { name: "Hysteria", runes: ["Shael", "Ko", "Eld"], slots: ["armor"], bases: ["Body Armor"], level: 39, patch: "3.0",
    note: "Armor half of the former Hustle",
    stats: ["+65% Faster Run/Walk", "+40% Increased Attack Speed", "+20% Faster Hit Recovery", "+6 to Evade", "+10 to Dexterity", "50% Slower Stamina Drain", "All Resistances +10"] },
  { name: "Kingslayer", runes: ["Mal", "Um", "Gul", "Fal"], slots: ["weapon"], bases: ["Swords", "Axes"], level: 53, patch: "1.10",
    stats: ["+30% Increased Attack Speed", "+230-270% Enhanced Damage", "-25% Target Defense", "20% Bonus to Attack Rating", "33% Chance of Crushing Blow", "50% Chance of Open Wounds", "+1 to Vengeance", "Prevent Monster Heal", "+10 to Strength", "40% Extra Gold from Monsters"] },
  { name: "Lawbringer", runes: ["Amn", "Lem", "Ko"], slots: ["weapon"], bases: ["Swords", "Hammers", "Scepters"], level: 43, patch: "1.10",
    stats: ["20% Chance to Cast Level 15 Decrepify on Striking", "Level 16-18 Sanctuary Aura When Equipped", "-50% Target Defense", "Adds 150-210 Fire Damage", "Adds 130-180 Cold Damage", "7% Life Stolen per Hit", "Slain Monsters Rest in Peace", "+200-250 Defense vs. Missile", "+10 to Dexterity", "75% Extra Gold from Monsters"] },
  { name: "Leaf", runes: ["Tir", "Ral"], slots: ["weapon"], bases: ["Staves"], level: 19, patch: "1.09",
    stats: ["+3 to Fire Skills", "Adds 5-30 Fire Damage", "+3 to Inferno (Sorceress Only)", "+3 to Warmth (Sorceress Only)", "+3 to Fire Bolt (Sorceress Only)", "+(2 per level) Defense", "Cold Resist +33%", "+2 to Mana after each Kill"] },
  { name: "Lionheart", runes: ["Hel", "Lum", "Fal"], slots: ["armor"], bases: ["Body Armor"], level: 41, patch: "1.09",
    stats: ["+20% Enhanced Damage", "Requirements -15%", "+25 to Strength", "+15 to Dexterity", "+20 to Vitality", "+10 to Energy", "+50 to Life", "All Resistances +30"] },
  { name: "Metamorphosis", runes: ["Io", "Cham", "Fal"], slots: ["helm"], bases: ["Helms"], level: 67, patch: "2.6",
    stats: ["100% Chance to Cast Mark of the Wolf on Striking in Werewolf Form", "100% Chance to Cast Mark of the Bear on Striking in Werebear Form", "+5 to Shape Shifting Skills (Druid Only)", "+25% Chance of Crushing Blow", "+50-80% Enhanced Defense", "+10 to Strength", "+10 to Vitality", "All Resistances +10", "Cannot Be Frozen"] },
  { name: "Mist", runes: ["Cham", "Shael", "Gul", "Thul", "Ith"], slots: ["weapon"], bases: ["Bows", "Crossbows"], level: 67, patch: "2.4",
    stats: ["Level 8-12 Concentration Aura When Equipped", "+3 to All Skills", "+20% Increased Attack Speed", "+100% Chance to Pierce", "+325-375% Enhanced Damage", "+9 to Maximum Damage", "20% Bonus to Attack Rating", "Adds 3-14 Cold Damage", "Freezes Target +3", "+24 to Vitality", "All Resistances +40"] },
  { name: "Obedience", runes: ["Hel", "Ko", "Thul", "Eth", "Fal"], slots: ["weapon"], bases: ["Polearms", "Spears"], level: 41, patch: "1.10",
    stats: ["30% Chance to Cast Level 21 Enchant When You Kill an Enemy", "+40% Faster Hit Recovery", "+370% Enhanced Damage", "-25% Target Defense", "Adds 3-14 Cold Damage", "-25% to Enemy Poison Resistance", "40% Chance of Crushing Blow", "Prevent Monster Heal", "+200-300 Defense", "+10 to Strength", "+10 to Dexterity", "All Resistances +20-30"] },
  { name: "Obsession", runes: ["Zod", "Ist", "Lem", "Lum", "Io", "Nef"], slots: ["weapon"], bases: ["Staves"], level: 69, patch: "2.4",
    stats: ["Indestructible", "24% Chance to Cast Level 10 Weaken When Struck", "+4 to All Skills", "+65% Faster Cast Rate", "+60% Faster Hit Recovery", "Knockback", "+10 to Vitality", "Increase Maximum Life 15-25%", "Regenerate Mana 15-30%", "All Resistances +60-70", "75% Extra Gold from Monsters", "30% Better Chance of Getting Magic Items"] },
  { name: "Peace", runes: ["Shael", "Thul", "Amn"], slots: ["armor"], bases: ["Body Armor"], level: 29, patch: "1.11",
    stats: ["4% Chance to Cast Level 5 Slow Missiles When Struck", "2% Chance to Cast Level 15 Valkyrie on Striking", "+2 to Amazon Skill Levels", "+20% Faster Hit Recovery", "+2 to Critical Strike", "Cold Resist +30%", "Attacker Takes Damage of 14"] },
  { name: "Pride", runes: ["Cham", "Sur", "Io", "Lo"], slots: ["weapon"], bases: ["Polearms", "Spears"], level: 67, patch: "1.10",
    stats: ["25% Chance to Cast Level 17 Fire Wall When Struck", "Level 16-20 Concentration Aura When Equipped", "260-300% Bonus to Attack Rating", "+1 to Maximum Damage (per level)", "Adds 50-280 Lightning Damage", "20% Deadly Strike", "Hit Blinds Target", "Freezes Target +3", "+10 to Vitality", "Replenish Life +8", "(1.875 per level)% Extra Gold from Monsters"] },
  { name: "Rhyme", runes: ["Shael", "Eth"], slots: ["shield"], bases: ["Shields"], level: 29, patch: "1.09",
    stats: ["+40% Faster Block Rate", "20% Increased Chance of Blocking", "Regenerate Mana 15%", "All Resistances +25", "Cannot Be Frozen", "50% Extra Gold from Monsters", "25% Better Chance of Getting Magic Items"] },
  { name: "Smoke", runes: ["Nef", "Lum"], slots: ["armor"], bases: ["Body Armor"], level: 37, patch: "1.09",
    stats: ["+20% Faster Hit Recovery", "+75% Enhanced Defense", "+280 Defense vs. Missile", "+10 to Energy", "All Resistances +50", "-1 to Light Radius"] },
  { name: "Steel", runes: ["Tir", "El"], slots: ["weapon"], bases: ["Swords", "Axes", "Maces"], level: 13, patch: "1.09",
    stats: ["+25% Increased Attack Speed", "+20% Enhanced Damage", "+3 to Minimum Damage", "+3 to Maximum Damage", "+50 to Attack Rating", "50% Chance of Open Wounds", "+2 to Mana after each Kill", "+1 to Light Radius"] },
  { name: "Treachery", runes: ["Shael", "Thul", "Lem"], slots: ["armor"], bases: ["Body Armor"], level: 43, patch: "1.11",
    stats: ["5% Chance to Cast Level 15 Fade When Struck", "25% Chance to Cast Level 15 Venom on Striking", "+2 to Assassin Skills", "+45% Increased Attack Speed", "+20% Faster Hit Recovery", "Cold Resist +30%", "50% Extra Gold from Monsters"] },
  { name: "Unbending Will", runes: ["Fal", "Io", "Ith", "Eld", "El", "Hel"], slots: ["weapon"], bases: ["Swords"], level: 41, patch: "2.4",
    stats: ["18% Chance to Cast Level 18 Taunt on Striking", "+3 to Combat Skills (Barbarian Only)", "+20-30% Increased Attack Speed", "+300-350% Enhanced Damage", "+9 to Maximum Damage", "+50 to Attack Rating", "+75% Damage to Undead", "8-10% Life Stolen per Hit", "Prevent Monster Heal", "+10 to Strength", "+10 to Vitality", "Damage Reduced by 8"] },
  { name: "White", runes: ["Dol", "Io"], slots: ["weapon"], bases: ["Wands"], level: 35, patch: "1.09",
    stats: ["Hit Causes Monster to Flee 25%", "+10 to Vitality", "+3 to Poison and Bone Skills (Necromancer Only)", "+3 to Bone Armor", "+2 to Bone Spear", "+4 to Skeleton Mastery", "Magic Damage Reduced by 4", "+20% Faster Cast Rate", "+13 to Mana"] },

  { name: "Void", runes: ["Thul", "Zod", "Ist"], slots: ["weapon"], bases: ["Daggers"], level: 69, patch: "3.0",
    stats: ["Indestructible", "+2 to All Skills", "+40% Faster Cast Rate", "+10-15% to Magic Skill Damage", "+1-3 to Abyss", "+8-12 to All Attributes", "Level 4 Decrepify (Charges)"] },
  { name: "Ritual", runes: ["Amn", "Shael", "Ohm"], slots: ["weapon"], bases: ["Daggers"], level: 57, patch: "3.0",
    stats: ["13% Chance to Cast Level 1 Sigil Death When Struck", "+40% Increased Attack Speed", "+250-320% Enhanced Damage", "+150-250% Damage to Demons", "+200-260% Bonus to Attack Rating"] },
  { name: "Coven", runes: ["Ist", "Ral", "Io"], slots: ["helm"], bases: ["Helms"], level: 51, patch: "3.0",
    stats: ["5% Chance to Cast Level 10 Sigil Lethargy When Struck", "+1 to All Skills", "+20% Faster Cast Rate", "+30-50% Enhanced Defense", "+1-5 Life after each Kill"] },
  { name: "Authority", runes: ["Hel", "Shael", "Ral"], slots: ["armor"], bases: ["Body Armor"], level: 29, patch: "3.0",
    stats: ["2% Chance to Cast Level 10 Psychic Ward When Struck", "10% Chance to Cast Level 15 Miasma Chain on Striking", "+2 to Warlock Skill Levels", "+40-60% Enhanced Defense", "Requirements -15%"] },
  { name: "Vigilance", runes: ["Dol", "Gul"], slots: ["shield"], bases: ["Shields", "Grimoires", "Shrunken Heads"], level: 53, patch: "3.0",
    stats: ["5% Chance to Cast Level 10 Ring of Fire When Struck", "+10% Faster Run/Walk", "+30% Faster Block Rate", "+20-40 to Life", "+20-40 to Mana", "All Resistances +25-35"] },
  { name: "Ancients' Pledge", runes: ["Ral", "Ort", "Tal"], slots: ["shield"], bases: ["Shields"], level: 21, patch: "1.09",
    stats: ["+50% Enhanced Defense", "Cold Resist +43%", "Fire Resist +48%", "Lightning Resist +48%", "Poison Resist +48%", "10% Damage Taken Goes to Mana"] },
  { name: "Black", runes: ["Thul", "Io", "Nef"], slots: ["weapon"], bases: ["Clubs", "Hammers", "Maces"], level: 35, patch: "1.09",
    stats: ["+15% Increased Attack Speed", "+120% Enhanced Damage", "+200 to Attack Rating", "Adds 3-14 Cold Damage", "40% Chance of Crushing Blow", "Knockback", "+10 to Vitality", "Magic Damage Reduced by 2", "Level 4 Corpse Explosion (12 Charges)"] },
  { name: "Brand", runes: ["Jah", "Lo", "Mal", "Gul"], slots: ["weapon"], bases: ["Bows", "Crossbows"], level: 65, patch: "1.10",
    stats: ["35% Chance to Cast Level 14 Amplify Damage When Struck", "100% Chance to Cast Level 18 Bone Spear on Striking", "Fires Explosive Arrows or Bolts (15)", "+260-340% Enhanced Damage", "Ignore Target's Defense", "20% Bonus to Attack Rating", "+280-330% Damage to Demons", "20% Deadly Strike", "Prevent Monster Heal", "Knockback"] },
  { name: "Bulwark", runes: ["Shael", "Io", "Sol"], slots: ["helm"], bases: ["Helms"], level: 35, patch: "2.6",
    stats: ["+20% Faster Hit Recovery", "4-6% Life Stolen per Hit", "+75-100% Enhanced Defense", "+10 to Vitality", "Replenish Life +30", "Physical Damage Taken Reduced by 10-15%"] },
  { name: "Chaos", runes: ["Fal", "Ohm", "Um"], slots: ["weapon"], bases: ["Claws"], level: 57, patch: "1.10",
    stats: ["9% Chance to Cast Level 11 Frozen Orb on Striking", "11% Chance to Cast Level 9 Charged Bolt on Striking", "+35% Increased Attack Speed", "+290-340% Enhanced Damage", "Adds 216-471 Magic Damage", "25% Chance of Open Wounds", "+1 to Whirlwind", "+10 to Strength", "+15 Life after each Kill"] },
  { name: "Cure", runes: ["Shael", "Io", "Tal"], slots: ["helm"], bases: ["Helms"], level: 35, patch: "2.6",
    stats: ["Level 1 Cleansing Aura When Equipped", "+20% Faster Hit Recovery", "+75-100% Enhanced Defense", "+10 to Vitality", "Poison Resist +40-60%", "50% Poison Length Reduction"] },
  { name: "Delirium", runes: ["Lem", "Ist", "Io"], slots: ["helm"], bases: ["Helms"], level: 51, patch: "1.10",
    stats: ["1% Chance to Cast Level 50 Delirium When Struck", "6% Chance to Cast Level 14 Mind Blast When Struck", "14% Chance to Cast Level 13 Terror When Struck", "11% Chance to Cast Level 18 Confuse on Striking", "+2 to All Skills", "+261 Defense", "+10 to Vitality", "50% Extra Gold from Monsters", "25% Better Chance of Getting Magic Items"] },
  { name: "Destruction", runes: ["Vex", "Lo", "Ber", "Jah", "Ko"], slots: ["weapon"], bases: ["Polearms", "Swords"], level: 65, patch: "1.10",
    stats: ["23% Chance to Cast Level 12 Volcano on Striking", "5% Chance to Cast Level 23 Molten Boulder on Striking", "100% Chance to Cast Level 45 Meteor When You Die", "15% Chance to Cast Level 22 Nova on Attack", "+350% Enhanced Damage", "Ignore Target's Defense", "Adds 100-180 Magic Damage", "7% Mana Stolen per Hit", "20% Chance of Crushing Blow", "20% Deadly Strike", "Prevent Monster Heal", "+10 to Dexterity"] },
  { name: "Dragon", runes: ["Sur", "Lo", "Sol"], slots: ["armor", "shield"], bases: ["Body Armor", "Shields"], level: 61, patch: "1.10",
    stats: ["20% Chance to Cast Level 18 Venom When Struck", "12% Chance to Cast Level 15 Hydra on Striking", "Level 14 Holy Fire Aura When Equipped", "+360 Defense", "+230 Defense vs. Missile", "+3-5 to All Attributes", "+(0.375 per level) to Strength", "+5% to Maximum Lightning Resist", "Damage Reduced by 7"] },
  { name: "Duress", runes: ["Shael", "Um", "Thul"], slots: ["armor"], bases: ["Body Armor"], level: 47, patch: "1.10",
    stats: ["+40% Faster Hit Recovery", "+10-20% Enhanced Damage", "Adds 37-133 Cold Damage", "15% Chance of Crushing Blow", "33% Chance of Open Wounds", "+150-200% Enhanced Defense", "-20% Slower Stamina Drain", "Cold Resist +45%", "Lightning Resist +15%", "Fire Resist +15%", "Poison Resist +15%"] },
  { name: "Edge", runes: ["Tir", "Tal", "Amn"], slots: ["weapon"], bases: ["Bows", "Crossbows"], level: 25, patch: "1.10",
    stats: ["Level 15 Thorns Aura When Equipped", "+35% Increased Attack Speed", "+320-380% Damage to Demons", "+280% Damage to Undead", "+75 Poison Damage over 5 Seconds", "7% Life Stolen per Hit", "Prevent Monster Heal", "+5-10 to All Attributes", "+2 to Mana after each Kill", "Reduces All Vendor Prices 15%"] },
  { name: "Enlightenment", runes: ["Pul", "Ral", "Sol"], slots: ["armor"], bases: ["Body Armor"], level: 45, patch: "1.11",
    stats: ["5% Chance to Cast Level 15 Blaze When Struck", "5% Chance to Cast Level 15 Fire Ball on Striking", "+2 to Sorceress Skill Levels", "+1 to Warmth", "+30% Enhanced Defense", "Fire Resist +30%", "Damage Reduced by 7"] },
  { name: "Eternity", runes: ["Amn", "Ber", "Ist", "Sol", "Sur"], slots: ["weapon"], bases: ["Melee Weapons"], level: 63, patch: "1.10",
    stats: ["Indestructible", "+260-310% Enhanced Damage", "+9 to Minimum Damage", "7% Life Stolen per Hit", "20% Chance of Crushing Blow", "Hit Blinds Target", "Slows Target by 33%", "Regenerate Mana 16%", "Replenish Life +16", "Cannot Be Frozen", "30% Better Chance of Getting Magic Items", "Level 8 Revive (88 Charges)"] },
  { name: "Famine", runes: ["Fal", "Ohm", "Ort", "Jah"], slots: ["weapon"], bases: ["Axes", "Hammers"], level: 65, patch: "1.10",
    stats: ["+30% Increased Attack Speed", "+320-370% Enhanced Damage", "Ignore Target's Defense", "Adds 180-200 Magic Damage", "Adds 50-200 Fire Damage", "Adds 51-250 Lightning Damage", "Adds 50-200 Cold Damage", "12% Life Stolen per Hit", "Prevent Monster Heal", "+10 to Strength"] },
  { name: "Flickering Flame", runes: ["Nef", "Pul", "Vex"], slots: ["helm"], bases: ["Helms"], level: 55, patch: "2.4",
    stats: ["Level 4-8 Resist Fire Aura When Equipped", "+3 to Fire Skills", "-10-15% to Enemy Fire Resistance", "+30% Enhanced Defense", "+30 Defense vs. Missile", "+50-75 to Mana", "Half Freeze Duration", "+5% to Maximum Fire Resist", "Poison Length Reduced by 50%"] },
  { name: "Gloom", runes: ["Fal", "Um", "Pul"], slots: ["armor"], bases: ["Body Armor"], level: 47, patch: "1.10",
    stats: ["15% Chance to Cast Level 3 Dim Vision When Struck", "+10% Faster Hit Recovery", "+200-260% Enhanced Defense", "+10 to Strength", "All Resistances +45", "Half Freeze Duration", "5% Damage Taken Goes to Mana", "-3 to Light Radius"] },
  { name: "Ground", runes: ["Shael", "Io", "Ort"], slots: ["helm"], bases: ["Helms"], level: 35, patch: "2.6",
    stats: ["+20% Faster Hit Recovery", "+75-100% Enhanced Defense", "+10 to Vitality", "Lightning Resist +40-60%", "Lightning Absorb 10-15%"] },
  { name: "Hand of Justice", runes: ["Sur", "Cham", "Amn", "Lo"], slots: ["weapon"], bases: ["All Weapons"], level: 67, patch: "1.10",
    stats: ["100% Chance to Cast Level 36 Blaze When You Level-Up", "100% Chance to Cast Level 48 Meteor When You Die", "Level 16 Holy Fire Aura When Equipped", "+33% Increased Attack Speed", "+280-330% Enhanced Damage", "Ignore Target's Defense", "-20% to Enemy Fire Resistance", "7% Life Stolen per Hit", "20% Deadly Strike", "Hit Blinds Target", "Freezes Target +3"] },
  { name: "Harmony", runes: ["Tir", "Ith", "Sol", "Ko"], slots: ["weapon"], bases: ["Bows", "Crossbows"], level: 39, patch: "1.10",
    stats: ["Level 10 Vigor Aura When Equipped", "+200-275% Enhanced Damage", "+9 to Minimum Damage", "+9 to Maximum Damage", "Adds 55-160 Fire, Lightning and Cold Damage", "+2-6 to Valkyrie", "+10 to Dexterity", "Regenerate Mana 20%", "+2 to Mana after each Kill", "+2 to Light Radius", "Level 20 Revive (25 Charges)"] },
  { name: "Hearth", runes: ["Shael", "Io", "Thul"], slots: ["helm"], bases: ["Helms"], level: 35, patch: "2.6",
    stats: ["+20% Faster Hit Recovery", "+75-100% Enhanced Defense", "+10 to Vitality", "Cold Resist +40-60%", "Cold Absorb 10-15%", "Cannot Be Frozen"] },
  { name: "Holy Thunder", runes: ["Eth", "Ral", "Ort", "Tal"], slots: ["weapon"], bases: ["Scepters"], level: 21, patch: "1.09",
    stats: ["+60% Enhanced Damage", "-25% Target Defense", "Adds 5-30 Fire Damage", "Adds 21-110 Lightning Damage", "+75 Poison Damage over 5 Seconds", "+3 to Holy Shock (Paladin Only)", "+5% to Maximum Lightning Resist", "Lightning Resist +60%", "Level 7 Chain Lightning (60 Charges)"] },
  { name: "Ice", runes: ["Amn", "Shael", "Jah", "Lo"], slots: ["weapon"], bases: ["Bows", "Crossbows"], level: 65, patch: "1.10",
    stats: ["100% Chance to Cast Level 40 Blizzard When You Level-Up", "25% Chance to Cast Level 22 Frost Nova on Striking", "Level 18 Holy Freeze Aura When Equipped", "+20% Increased Attack Speed", "+140-210% Enhanced Damage", "Ignore Target's Defense", "+25-30% to Cold Skill Damage", "-20% to Enemy Cold Resistance", "7% Life Stolen per Hit", "20% Deadly Strike", "(3.125 per level)% Extra Gold from Monsters"] },
  { name: "King's Grace", runes: ["Amn", "Ral", "Thul"], slots: ["weapon"], bases: ["Swords", "Scepters"], level: 25, patch: "1.09",
    stats: ["+100% Enhanced Damage", "+150 to Attack Rating", "+100% Damage to Demons", "+100 to Attack Rating against Demons", "+50% Damage to Undead", "+100 to Attack Rating against Undead", "Adds 5-30 Fire Damage", "Adds 3-14 Cold Damage", "7% Life Stolen per Hit"] },
  { name: "Last Wish", runes: ["Jah", "Mal", "Jah", "Sur", "Jah", "Ber"], slots: ["weapon"], bases: ["Swords", "Hammers", "Axes"], level: 65, patch: "1.10",
    stats: ["6% Chance to Cast Level 11 Fade When Struck", "10% Chance to Cast Level 18 Life Tap on Striking", "20% Chance to Cast Level 20 Charged Bolt on Attack", "Level 17 Might Aura When Equipped", "+330-375% Enhanced Damage", "Ignore Target's Defense", "60-70% Chance of Crushing Blow", "Prevent Monster Heal", "Hit Blinds Target", "10-20% Better Chance of Getting Magic Items"] },
  { name: "Malice", runes: ["Ith", "El", "Eth"], slots: ["weapon"], bases: ["Melee Weapons"], level: 15, patch: "1.09",
    stats: ["+33% Enhanced Damage", "+9 to Maximum Damage", "-25% Target Defense", "+50 to Attack Rating", "100% Chance of Open Wounds", "Prevent Monster Heal", "-100 to Monster Defense per Hit", "Drain Life -5"] },
  { name: "Melody", runes: ["Shael", "Ko", "Nef"], slots: ["weapon"], bases: ["Bows", "Crossbows"], level: 39, patch: "1.09",
    stats: ["+3 to Bow and Crossbow Skills (Amazon Only)", "+20% Increased Attack Speed", "+50% Enhanced Damage", "+300% Damage to Undead", "+3 to Slow Missiles", "+3 to Dodge", "+3 to Critical Strike", "Knockback", "+10 to Dexterity"] },
  { name: "Memory", runes: ["Lum", "Io", "Sol", "Eth"], slots: ["weapon"], bases: ["Staves"], level: 37, patch: "1.09",
    stats: ["+3 to Sorceress Skill Levels", "+33% Faster Cast Rate", "Increase Maximum Mana 20%", "+3 to Energy Shield", "+2 to Static Field", "+50% Enhanced Defense", "+10 to Vitality", "+10 to Energy", "Magic Damage Reduced by 7"] },
  { name: "Myth", runes: ["Hel", "Amn", "Nef"], slots: ["armor"], bases: ["Body Armor"], level: 25, patch: "1.11",
    stats: ["3% Chance to Cast Level 1 Howl When Struck", "10% Chance to Cast Level 1 Taunt on Striking", "+2 to Barbarian Skill Levels", "+30 Defense vs. Missile", "Replenish Life +10", "Attacker Takes Damage of 14", "Requirements -15%"] },
  { name: "Nadir", runes: ["Nef", "Tir"], slots: ["helm"], bases: ["Helms"], level: 13, patch: "1.09",
    stats: ["+50% Enhanced Defense", "+10 Defense", "+30 Defense vs. Missile", "+5 to Strength", "+2 to Mana after each Kill", "-33% Extra Gold from Monsters", "-3 to Light Radius", "Level 13 Cloak of Shadows (9 Charges)"] },
  { name: "Oath", runes: ["Shael", "Pul", "Mal", "Lum"], slots: ["weapon"], bases: ["Swords", "Axes", "Maces"], level: 49, patch: "1.10",
    stats: ["30% Chance to Cast Level 20 Bone Spirit on Striking", "Indestructible", "+50% Increased Attack Speed", "+210-340% Enhanced Damage", "+75% Damage to Demons", "+100 to Attack Rating against Demons", "Prevent Monster Heal", "+10 to Energy", "+10-15 Magic Absorb", "Level 16 Heart of Wolverine (20 Charges)", "Level 17 Iron Golem (14 Charges)"] },
  { name: "Passion", runes: ["Dol", "Ort", "Eld", "Lem"], slots: ["weapon"], bases: ["All Weapons"], level: 43, patch: "1.10",
    stats: ["+25% Increased Attack Speed", "+160-210% Enhanced Damage", "50-80% Bonus to Attack Rating", "+75% Damage to Undead", "Adds 1-50 Lightning Damage", "+1 to Berserk", "+1 to Zeal", "Hit Blinds Target +10", "Hit Causes Monster to Flee 25%", "75% Extra Gold from Monsters", "Level 3 Heart of Wolverine (12 Charges)"] },
  { name: "Pattern", runes: ["Tal", "Ort", "Thul"], slots: ["weapon"], bases: ["Claws"], level: 23, patch: "2.4",
    stats: ["+30% Faster Block Rate", "+40-80% Enhanced Damage", "10% Bonus to Attack Rating", "Adds 17-62 Fire Damage", "Adds 1-50 Lightning Damage", "Adds 3-14 Cold Damage", "+75 Poison Damage over 5 Seconds", "+6 to Strength", "+6 to Dexterity", "All Resistances +15"] },
  { name: "Phoenix", runes: ["Vex", "Vex", "Lo", "Jah"], slots: ["weapon", "shield"], bases: ["Weapons", "Shields"], level: 65, patch: "1.10",
    stats: ["100% Chance to Cast Level 40 Blaze When You Level-up", "40% Chance to Cast Level 22 Firestorm on Striking", "Level 10-15 Redemption Aura When Equipped", "+350-400% Enhanced Damage (Weapon)", "-28% to Enemy Fire Resistance", "+350-400 Defense vs. Missile", "+15-21 Fire Absorb", "+5% to Maximum Lightning / Fire Resist"] },
  { name: "Plague", runes: ["Cham", "Shael", "Um"], slots: ["weapon"], bases: ["Swords", "Claws", "Daggers"], level: 67, patch: "2.4",
    stats: ["20% Chance to Cast Level 12 Lower Resist when Struck", "25% Chance to Cast Level 15 Poison Nova on Striking", "Level 13-17 Cleansing Aura When Equipped", "+1-2 All Skills", "+20% Increased Attack Speed", "+220-320% Enhanced Damage", "-23% To Enemy Poison Resistance", "(0.3 per level)% Deadly Strike", "+25% Chance of Open Wounds", "Freezes Target +3"] },
  { name: "Principle", runes: ["Ral", "Gul", "Eld"], slots: ["armor"], bases: ["Body Armor"], level: 53, patch: "1.11",
    stats: ["100% Chance to Cast Level 5 Holy Bolt on Striking", "+2 to Paladin Skill Levels", "+50% Damage to Undead", "+100-150 to Life", "15% Slower Stamina Drain", "+5% to Maximum Poison Resist", "Fire Resist +30%"] },
  { name: "Prudence", runes: ["Mal", "Tir"], slots: ["armor"], bases: ["Body Armor"], level: 49, patch: "1.10",
    stats: ["+25% Faster Hit Recovery", "+140-170% Enhanced Defense", "All Resistances +25-35", "Damage Reduced by 3", "Magic Damage Reduced by 17", "+2 to Mana after each Kill", "+1 to Light Radius", "Repairs Durability 1 in 4 Seconds"] },
  { name: "Radiance", runes: ["Nef", "Sol", "Ith"], slots: ["helm"], bases: ["Helms"], level: 27, patch: "1.09",
    stats: ["+75% Enhanced Defense", "+30 Defense vs. Missile", "+10 to Vitality", "+10 to Energy", "+33 to Mana", "Damage Reduced by 7", "Magic Damage Reduced by 3", "15% Damage Taken Goes to Mana", "+5 to Light Radius"] },
  { name: "Rain", runes: ["Ort", "Mal", "Ith"], slots: ["armor"], bases: ["Body Armor"], level: 49, patch: "1.11",
    stats: ["5% Chance to Cast Level 15 Cyclone Armor When Struck", "5% Chance to Cast Level 15 Twister on Striking", "+2 to Druid Skills", "+100-150 to Mana", "Lightning Resist +30%", "Magic Damage Reduced by 7", "15% Damage Taken Goes to Mana"] },
  { name: "Rift", runes: ["Hel", "Ko", "Lem", "Gul"], slots: ["weapon"], bases: ["Polearms", "Scepters"], level: 53, patch: "1.10",
    stats: ["20% Chance to Cast Level 16 Tornado on Striking", "16% Chance to Cast Level 21 Frozen Orb on Attack", "20% Bonus to Attack Rating", "Adds 160-250 Magic Damage", "Adds 60-180 Fire Damage", "+5-10 to All Stats", "+10 to Dexterity", "38% Damage Taken Goes to Mana", "75% Extra Gold from Monsters", "Level 15 Iron Maiden (40 Charges)", "Requirements -20%"] },
  { name: "Sanctuary", runes: ["Ko", "Ko", "Mal"], slots: ["shield"], bases: ["Shields"], level: 49, patch: "1.10",
    stats: ["+20% Faster Hit Recovery", "+20% Faster Block Rate", "20% Increased Chance of Blocking", "+130-160% Enhanced Defense", "+250 Defense vs. Missile", "+20 to Dexterity", "All Resistances +50-70", "Magic Damage Reduced by 7", "Level 12 Slow Missiles (60 Charges)"] },
  { name: "Silence", runes: ["Dol", "Eld", "Hel", "Ist", "Tir", "Vex"], slots: ["weapon"], bases: ["All Weapons"], level: 55, patch: "1.09",
    stats: ["+2 to All Skills", "+20% Increased Attack Speed", "+20% Faster Hit Recovery", "+200% Enhanced Damage", "+75% Damage to Undead", "Requirements -20%", "Hit Causes Monster to Flee 25%", "Hit Blinds Target +33", "All Resistances +75", "+2 to Mana after each Kill", "30% Better Chance of Getting Magic Items"] },
  { name: "Splendor", runes: ["Eth", "Lum"], slots: ["shield"], bases: ["Shields"], level: 37, patch: "1.10",
    stats: ["+1 to All Skills", "+10% Faster Cast Rate", "+20% Faster Block Rate", "+60-100% Enhanced Defense", "+10 to Energy", "Regenerate Mana 15%", "50% Extra Gold from Monsters", "20% Better Chance of Getting Magic Items", "+3 to Light Radius"] },
  { name: "Stone", runes: ["Shael", "Um", "Pul", "Lum"], slots: ["armor"], bases: ["Body Armor"], level: 47, patch: "1.10",
    stats: ["+60% Faster Hit Recovery", "+250-290% Enhanced Defense", "+300 Defense vs. Missile", "+16 to Strength", "+16 to Vitality", "+10 to Energy", "All Resistances +15", "Level 16 Molten Boulder (80 Charges)", "Level 16 Clay Golem (16 Charges)"] },
  { name: "Strength", runes: ["Amn", "Tir"], slots: ["weapon"], bases: ["Melee Weapons"], level: 25, patch: "1.09",
    stats: ["+35% Enhanced Damage", "7% Life Stolen per Hit", "25% Chance of Crushing Blow", "+20 to Strength", "+10 to Vitality", "+2 to Mana after each Kill"] },
  { name: "Temper", runes: ["Shael", "Io", "Ral"], slots: ["helm"], bases: ["Helms"], level: 35, patch: "2.6",
    stats: ["+20% Faster Hit Recovery", "+75-100% Enhanced Defense", "+10 to Vitality", "Fire Resist +40-60%", "Fire Absorb 10-15%"] },
  { name: "Venom", runes: ["Tal", "Dol", "Mal"], slots: ["weapon"], bases: ["All Weapons"], level: 49, patch: "1.09",
    stats: ["Ignore Target's Defense", "+273 Poison Damage over 6 Seconds", "7% Mana Stolen per Hit", "Prevent Monster Heal", "Hit Causes Monster to Flee 25%", "Level 13 Poison Nova (11 Charges)", "Level 15 Poison Explosion (27 Charges)"] },
  { name: "Voice of Reason", runes: ["Lem", "Ko", "El", "Eld"], slots: ["weapon"], bases: ["Swords", "Maces"], level: 43, patch: "1.10",
    stats: ["15% Chance to Cast Level 13 Frozen Orb on Striking", "18% Chance to Cast Level 20 Ice Blast on Striking", "+50 to Attack Rating", "+220-350% Damage to Demons", "+355-375% Damage to Undead", "Adds 100-220 Cold Damage", "-24% to Enemy Cold Resistance", "+10 to Dexterity", "Cannot Be Frozen", "75% Extra Gold from Monsters"] },
  { name: "Wealth", runes: ["Lem", "Ko", "Tir"], slots: ["armor"], bases: ["Body Armor"], level: 43, patch: "1.09",
    stats: ["+10 to Dexterity", "+2 to Mana after each Kill", "300% Extra Gold from Monsters", "100% Better Chance of Getting Magic Items"] },
  { name: "Wind", runes: ["Sur", "El"], slots: ["weapon"], bases: ["Melee Weapons"], level: 61, patch: "1.10",
    stats: ["10% Chance to Cast Level 9 Tornado on Striking", "+20% Faster Run/Walk", "+40% Increased Attack Speed", "+15% Faster Hit Recovery", "+120-160% Enhanced Damage", "-50% Target Defense", "+50 to Attack Rating", "Hit Blinds Target", "+1 to Light Radius", "Level 13 Twister (127 Charges)"] },
  { name: "Wisdom", runes: ["Pul", "Ith", "Eld"], slots: ["helm"], bases: ["Helms"], level: 45, patch: "2.4",
    stats: ["+33% Piercing Attack", "+15-25% Bonus to Attack Rating", "4-8% Mana Stolen per Hit", "+30% Enhanced Defense", "+10 to Energy", "15% Slower Stamina Drain", "Cannot Be Frozen", "+5 Mana After Each Kill", "15% Damage Taken Goes to Mana"] },
  { name: "Wrath", runes: ["Pul", "Lum", "Ber", "Mal"], slots: ["weapon"], bases: ["Bows", "Crossbows"], level: 63, patch: "1.10",
    stats: ["30% Chance to Cast Level 1 Decrepify on Striking", "5% Chance to Cast Level 10 Life Tap on Striking", "+375% Damage to Demons", "+100 to Attack Rating against Demons", "+250-300% Damage to Undead", "Adds 85-120 Magic Damage", "Adds 41-240 Lightning Damage", "20% Chance of Crushing Blow", "Prevent Monster Heal", "+10 to Energy", "Cannot Be Frozen"] },
  { name: "Zephyr", runes: ["Ort", "Eth"], slots: ["weapon"], bases: ["Bows", "Crossbows"], level: 21, patch: "1.09",
    stats: ["7% Chance to Cast Level 1 Twister When Struck", "+25% Faster Run/Walk", "+25% Increased Attack Speed", "+33% Enhanced Damage", "-25% Target Defense", "+66 to Attack Rating", "Adds 1-50 Lightning Damage", "+25 Defense"] },
];

export const RUNEWORD_TIERS = {
  S: ["Call to Arms", "Enigma", "Flickering Flame", "Fortitude", "Grief", "Heart of the Oak", "Infinity", "Insight", "Last Wish", "Phoenix", "Spirit", "Stealth"],
  A: ["Ancients' Pledge", "Beast", "Obsession", "Breath of the Dying", "Bulwark", "Chains of Honor", "Coven", "Crescent Moon", "Doom", "Dream", "Edge", "Leaf", "Lore", "Mania", "Oath", "Obedience", "Plague", "Rhyme", "Smoke", "Treachery", "White", "Wisdom", "Mosaic"],
  B: ["Authority", "Black", "Bramble", "Cure", "Dragon", "Duress", "Exile", "Faith", "Hand of Justice", "Harmony", "Hysteria", "Ice", "Lawbringer", "Memory", "Metamorphosis", "Peace", "Pride", "Sanctuary", "Unbending Will", "Void", "Wealth"],
  C: ["Bone", "Brand", "Chaos", "Death", "Delirium", "Ground", "Hearth", "Kingslayer", "Lionheart", "Malice", "Melody", "Mist", "Myth", "Nadir", "Passion", "Pattern", "Prudence", "Rain", "Rift", "Splendor", "Steel", "Stone", "Strength", "Temper", "Voice of Reason", "Zephyr"],
  D: ["Enlightenment", "Fury", "Gloom", "Honor", "Principle", "Silence", "Vigilance", "Wrath"],
  F: ["Destruction", "Eternity", "Famine", "Holy Thunder", "King's Grace", "Radiance", "Ritual", "Venom", "Wind"],
};

// Notes on the tier list: Edge is rated A as a gamble-only base; Fortitude and
// Phoenix are rated lower as weapons (A and C) than as armor/shield (S).
// Mosaic is not on the maxroll list; it is placed in A based on its use in
// both maxroll Assassin martial arts builds.

export const BUILDS = [
  // Amazon
  { name: "Lightning Fury", cls: "ama", tier: "S",
    uses: ["Infinity", "Enigma", "Chains of Honor", "Treachery", "Peace", "Smoke", "Hysteria", "Lionheart", "Duress", "Wealth", "Fortitude", "Call to Arms", "Spirit", "Rhyme", "Harmony", "Mania", "Insight", "Sanctuary"],
    merc: ["Infinity", "Insight", "Mania"] },
  { name: "Lightning Strike", cls: "ama", tier: "A",
    uses: ["Infinity", "Call to Arms", "Enigma", "Treachery", "Spirit"],
    merc: ["Insight", "Mania", "Faith", "Infinity", "Fortitude"] },
  { name: "Strafe", cls: "ama", tier: "A",
    uses: ["Faith", "Mist", "Mania", "Call to Arms", "Fortitude", "Treachery", "Enigma", "Chains of Honor", "Lionheart"],
    merc: ["Insight", "Strength", "Obedience", "Pride", "Smoke", "Duress"] },
  { name: "Multiple Shot", cls: "ama", tier: "B",
    uses: ["Mania", "Faith", "Harmony", "Insight", "Call to Arms", "Fortitude", "Enigma", "Chains of Honor", "Lionheart"],
    merc: ["Insight", "Obedience", "Pride", "Strength", "Smoke", "Treachery", "Duress"] },
  { name: "Freezing Arrow", cls: "ama", tier: "C",
    uses: ["Mania", "Faith", "Mist", "Melody", "Harmony", "Insight", "Call to Arms", "Spirit", "Ancients' Pledge", "Lore", "Wisdom", "Enigma", "Chains of Honor", "Treachery", "Peace", "Smoke", "Stealth"],
    merc: ["Insight", "Infinity"] },
  { name: "Exploding Arrow", cls: "ama", tier: "C",
    uses: ["Faith", "Phoenix", "Mist", "Melody", "Harmony", "Mania", "Call to Arms", "Flickering Flame", "Chains of Honor", "Enigma", "Peace", "Treachery"],
    merc: ["Insight", "Infinity", "Plague", "Lionheart", "Duress", "Fortitude"] },
  { name: "Plague Javelin", cls: "ama", tier: "C",
    uses: ["Peace", "Insight", "Enigma", "Spirit", "Plague", "Call to Arms", "Rhyme", "Ancients' Pledge"],
    merc: ["Plague", "Insight"] },
  { name: "Jab Fend", cls: "ama", tier: "D",
    uses: ["Breath of the Dying", "Obedience", "Harmony", "Enigma", "Fortitude", "Chains of Honor", "Hysteria", "Duress", "Lionheart", "Smoke"],
    merc: ["Breath of the Dying", "Obedience", "Mania", "Lawbringer", "Pride", "Faith"] },
  // Assassin
  { name: "Lightning Sentry", cls: "asn", tier: "S",
    uses: ["Enigma", "Treachery", "Stealth"],
    merc: ["Insight", "Infinity", "Plague", "Lionheart", "Duress", "Fortitude"] },
  { name: "Fire Blast", cls: "asn", tier: "A",
    uses: ["Heart of the Oak", "Call to Arms", "Spirit", "Rhyme", "Enigma", "Chains of Honor"],
    merc: ["Insight", "Infinity", "Plague", "Fortitude", "Treachery", "Lionheart", "Duress"] },
  { name: "Wake of Fire", cls: "asn", tier: "A",
    uses: ["Lore", "Stealth", "Ancients' Pledge", "Rhyme", "Heart of the Oak", "Spirit", "Phoenix", "Call to Arms"],
    merc: ["Insight", "Infinity"] },
  { name: "Dragon Talon", cls: "asn", tier: "A",
    uses: ["Mosaic", "Beast", "Call to Arms", "Spirit", "Chains of Honor", "Enigma", "Duress"],
    merc: [] },
  { name: "Dragon Tail", cls: "asn", tier: "B",
    uses: ["Mosaic", "Plague", "Phoenix"],
    merc: ["Infinity", "Lawbringer"] },
  { name: "Blade", cls: "asn", tier: "C",
    uses: ["Phoenix", "Spirit", "Rhyme", "Unbending Will", "Call to Arms", "Enigma", "Fortitude", "Chains of Honor", "Duress", "Treachery"],
    merc: ["Insight", "Obedience"] },
  // Barbarian
  { name: "Berserk", cls: "bar", tier: "S",
    uses: ["Grief", "Oath", "Harmony", "Rhyme", "Enigma", "Wealth"],
    merc: ["Insight", "Mania", "Breath of the Dying"] },
  { name: "Gold Find", cls: "bar", tier: "S",
    uses: ["Grief", "Oath", "Unbending Will", "Heart of the Oak", "Enigma"],
    merc: ["Insight", "Breath of the Dying", "Smoke", "Lionheart", "Treachery", "Duress", "Wealth"] },
  { name: "Double Throw", cls: "bar", tier: "A",
    uses: ["Enigma", "Fortitude", "Hysteria", "Lionheart", "Treachery", "Wealth", "Heart of the Oak"],
    merc: ["Faith", "Pride", "Insight", "Lawbringer"] },
  { name: "War Cry", cls: "bar", tier: "B",
    uses: ["Spirit", "Insight", "Call to Arms", "Enigma", "Ancients' Pledge"],
    merc: ["Insight", "Fortitude"] },
  { name: "Frenzy", cls: "bar", tier: "B",
    uses: ["Beast", "Grief", "Last Wish", "Breath of the Dying", "Oath", "Unbending Will", "Heart of the Oak", "Call to Arms", "Chains of Honor", "Enigma", "Fortitude", "Lionheart"],
    merc: ["Insight", "Lawbringer", "Treachery"] },
  { name: "Leap Attack", cls: "bar", tier: "C",
    uses: ["Unbending Will", "Grief", "Oath", "Breath of the Dying", "Death", "Spirit", "Phoenix", "Rhyme", "Heart of the Oak", "Call to Arms", "Enigma", "Fortitude", "Wealth", "Chains of Honor", "Treachery", "Hysteria", "Lionheart"],
    merc: ["Insight", "Lawbringer"] },
  { name: "Whirlwind", cls: "bar", tier: "C",
    uses: ["Beast", "Grief", "Last Wish", "Breath of the Dying", "Obedience", "Unbending Will", "Phoenix", "Heart of the Oak", "Chains of Honor", "Enigma", "Fortitude", "Lionheart"],
    merc: ["Insight", "Treachery", "Lawbringer"] },
  // Druid
  { name: "Fissure", cls: "dru", tier: "S",
    uses: ["Heart of the Oak", "Phoenix", "Spirit", "Leaf", "Call to Arms", "Harmony", "Enigma", "Wealth", "Chains of Honor", "Rain", "Smoke", "Treachery", "Rhyme", "Ancients' Pledge"],
    merc: ["Insight", "Lawbringer", "Crescent Moon", "Infinity", "Fortitude", "Duress"] },
  { name: "Tornado", cls: "dru", tier: "B",
    uses: ["Enigma", "Insight", "Spirit", "Harmony", "Call to Arms"],
    merc: ["Insight", "Lawbringer", "Infinity", "Grief", "Doom"] },
  { name: "Summon", cls: "dru", tier: "C",
    uses: ["Beast", "Spirit", "Call to Arms"],
    merc: ["Insight", "Mania", "Obedience", "Lawbringer", "Pride"] },
  { name: "Fury", cls: "dru", tier: "C",
    uses: ["Breath of the Dying", "Oath", "Grief", "Unbending Will", "Call to Arms", "Brand", "Harmony", "Spirit", "Phoenix", "Sanctuary", "Rhyme"],
    merc: ["Lawbringer", "Mania", "Insight", "Pride", "Faith"] },
  { name: "Maul", cls: "dru", tier: "D",
    uses: ["Breath of the Dying", "Grief", "Oath", "Unbending Will", "Hysteria", "Call to Arms", "Brand", "Harmony", "Phoenix", "Spirit", "Fortitude", "Chains of Honor", "Duress", "Treachery", "Enigma", "Lionheart"],
    merc: ["Lawbringer", "Mania", "Insight", "Faith", "Pride"] },
  // Necromancer
  { name: "Poison Nova", cls: "nec", tier: "S",
    uses: ["Enigma", "Bramble", "Insight", "Spirit", "Heart of the Oak", "Harmony", "Call to Arms"],
    merc: ["Infinity", "Insight", "Mania", "Lionheart"] },
  { name: "Summoner", cls: "nec", tier: "A",
    uses: ["Spirit", "Heart of the Oak", "Beast"],
    merc: ["Insight", "Infinity", "Bramble", "Fortitude", "Treachery", "Duress", "Wealth"] },
  { name: "Bone Spear", cls: "nec", tier: "C",
    uses: ["Spirit", "Heart of the Oak", "Enigma"],
    merc: ["Insight", "Fortitude"] },
  // Paladin
  { name: "Blessed Hammer", cls: "pal", tier: "S",
    uses: ["Spirit", "Phoenix", "Void", "Heart of the Oak", "Call to Arms", "Enigma", "Ancients' Pledge", "Rhyme", "Treachery"],
    merc: ["Insight"] },
  { name: "Fist of the Heavens", cls: "pal", tier: "S",
    uses: ["Heart of the Oak", "Spirit", "Call to Arms", "Ancients' Pledge", "Rhyme", "Enigma"],
    merc: ["Insight", "Fortitude", "Treachery", "Duress", "Wealth", "Lionheart"] },
  { name: "Smite", cls: "pal", tier: "S",
    uses: ["Grief", "Rhyme", "Hearth", "Last Wish", "Exile", "Sanctuary", "Call to Arms", "Spirit", "Chains of Honor", "Duress", "Enigma", "Treachery", "Smoke", "Hysteria"],
    merc: ["Insight"] },
  { name: "Dream", cls: "pal", tier: "A",
    uses: ["Dream", "Grief", "Crescent Moon", "Call to Arms", "Spirit", "Enigma", "Fortitude", "Chains of Honor", "Duress", "Last Wish"],
    merc: ["Insight", "Infinity", "Faith"] },
  { name: "Zeal", cls: "pal", tier: "B",
    uses: ["Grief", "Last Wish", "Doom", "Oath", "Unbending Will", "Hysteria", "Honor", "Enigma", "Fortitude", "Chains of Honor", "Stone", "Duress", "Treachery", "Lionheart", "Smoke", "Spirit", "Rhyme", "Sanctuary"],
    merc: ["Lawbringer", "Insight"] },
  { name: "Holy Fire", cls: "pal", tier: "B",
    uses: ["Insight", "Spirit", "Call to Arms"],
    merc: ["Insight", "Infinity", "Plague", "Crescent Moon", "Fortitude"] },
  // Sorceress
  { name: "Lightning", cls: "sor", tier: "S",
    uses: ["Enigma", "Call to Arms", "Harmony", "Insight", "Treachery"],
    merc: ["Infinity", "Insight", "Fortitude"] },
  { name: "Blizzard", cls: "sor", tier: "S",
    uses: ["Spirit", "Stealth", "Lore", "Ancients' Pledge", "Heart of the Oak", "Obsession", "Rhyme", "Call to Arms", "Memory"],
    merc: ["Insight", "Infinity", "Doom", "Fortitude", "Treachery", "Duress", "Smoke", "Lionheart"] },
  { name: "Fire Ball Meteor", cls: "sor", tier: "S",
    uses: ["Spirit", "Heart of the Oak", "Obsession", "Rhyme", "Ancients' Pledge", "Call to Arms", "Memory"],
    merc: ["Insight", "Infinity", "Smoke", "Lionheart", "Treachery", "Duress", "Fortitude"] },
  { name: "Nova", cls: "sor", tier: "S",
    uses: ["Spirit", "Stealth", "Lore", "Splendor", "Memory", "Call to Arms", "Heart of the Oak"],
    merc: ["Insight", "Infinity", "Crescent Moon", "Treachery", "Chains of Honor"] },
  { name: "Enchant", cls: "sor", tier: "A",
    uses: ["Spirit", "Leaf"],
    merc: ["Insight", "Infinity", "Breath of the Dying"] },
  { name: "Frost Nova", cls: "sor", tier: "B",
    uses: ["Call to Arms", "Rhyme", "Enigma", "Smoke", "Stealth"],
    merc: ["Insight", "Infinity", "Fortitude", "Treachery", "Chains of Honor", "Lionheart", "Duress"] },
  { name: "Hydra", cls: "sor", tier: "B",
    uses: ["Spirit", "Stealth", "Lore", "Ancients' Pledge", "Heart of the Oak", "Obsession", "Rhyme", "Call to Arms", "Memory"],
    merc: ["Insight", "Obedience", "Infinity", "Smoke", "Mania", "Treachery", "Duress", "Fortitude", "Chains of Honor"] },
  { name: "Fire Wall", cls: "sor", tier: "B",
    uses: ["Spirit", "Stealth", "Lore", "Ancients' Pledge", "Heart of the Oak", "Obsession", "Call to Arms", "Memory", "Rhyme"],
    merc: ["Insight", "Obedience", "Infinity", "Fortitude", "Treachery", "Duress", "Chains of Honor"] },
  { name: "Frozen Orb", cls: "sor", tier: "B",
    uses: ["Spirit", "Stealth", "Lore", "Ancients' Pledge", "Call to Arms", "Memory"],
    merc: ["Insight", "Obedience", "Infinity", "Smoke", "Mania", "Treachery", "Duress", "Fortitude", "Chains of Honor"] },
  // Warlock
  { name: "Echoing Strike", cls: "war", tier: "S",
    uses: ["Spirit", "Obsession", "Silence", "Fortitude", "Insight", "Plague", "Heart of the Oak", "Call to Arms", "Splendor", "Ancients' Pledge", "Rhyme", "Enigma", "Stealth", "Chains of Honor"],
    merc: ["Insight", "Doom", "Smoke", "Lionheart", "Duress", "Treachery", "Chains of Honor", "Fortitude"] },
  { name: "Fire", cls: "war", tier: "S",
    uses: ["Spirit", "Insight", "Leaf", "Phoenix", "Rhyme", "Ancients' Pledge", "Call to Arms"],
    merc: ["Insight", "Infinity"] },
  { name: "Abyss", cls: "war", tier: "A",
    uses: ["Void", "Heart of the Oak", "Spirit", "Plague", "Obsession", "Insight", "Call to Arms", "Enigma", "Stealth", "Chains of Honor", "Ancients' Pledge", "Rhyme"],
    merc: ["Insight", "Treachery", "Duress", "Fortitude", "Chains of Honor"] },
  { name: "Mirrored Blades", cls: "war", tier: "A",
    uses: ["Grief", "Enigma"],
    merc: ["Insight", "Pride", "Treachery", "Fortitude", "Chains of Honor"] },
  { name: "Blood Boil", cls: "war", tier: "B",
    uses: ["Enigma", "Stealth", "Chains of Honor", "Call to Arms", "Spirit", "Insight", "Phoenix", "Rhyme", "Ancients' Pledge", "Splendor"],
    merc: ["Infinity", "Insight", "Fortitude"] },
  { name: "Summoner", cls: "war", tier: "B",
    uses: ["Enigma", "Stealth", "Chains of Honor", "Rhyme", "Ancients' Pledge", "Spirit", "Insight", "Phoenix"],
    merc: ["Infinity", "Insight", "Treachery", "Duress", "Wealth", "Fortitude"] },
];
